# build
[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_VERSION = "14.18.1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  RUBY_VERSION = "2.6.2"
  NPM_VERSION = "8.1.2"
# Headers 
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=360000"
# redirects
[[redirects]]
  from = "http://inspiring-leaders.netlify.com/*"
  to = "https://www.inspiring-leaders.co.za/:splat"
  status = 301
  
[[redirects]]
  from = "https://inspiring-leaders.netlify.com/*"
  to = "https://www.inspiring-leaders.co.za/:splat"
  status = 301